name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Buildozer cache törlése
        run: rm -rf ~/.buildozer
    
      - name: Repository letöltése
        uses: actions/checkout@v4

      - name: Python telepítése (Python 3.10)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Buildozer és függőségek telepítése
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk
          pip install --upgrade pip setuptools wheel cython virtualenv
          pip install buildozer
      
      - name: Kézi `python-for-android` letöltés és telepítés
        run: |
          mkdir -p ~/.buildozer/android/platform
          git clone --depth 1 https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android
          cd ~/.buildozer/android/platform/python-for-android
          git submodule update --init --recursive
          pip install -e .

      - name: Android SDK és NDK beállítása
        run: |
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk
          export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

      - name: Buildozer inicializálása (csak ha szükséges)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          cat buildozer.spec  # Ellenőrizzük a beállításokat

      - name: Buildozer tisztítása és frissítése
        run: |
          buildozer android clean
          buildozer android update

      - name: APK fordítása
        run: |
          buildozer -v android debug  # A -v kapcsolóval több információt kapunk a hibákról

      - name: APK mentése a workflow eredményei közé
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk


