name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository letöltése
        uses: actions/checkout@v4

      - name: Szükséges csomagok telepítése
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk unzip wget

      - name: Android SDK letöltése és telepítése
        run: |
          mkdir -p $HOME/.buildozer/android
          cd $HOME/.buildozer/android
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          mkdir -p android-sdk/cmdline-tools
          unzip -q cmdline-tools.zip -d android-sdk/cmdline-tools
          mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          rm cmdline-tools.zip

      - name: PATH és környezeti változók beállítása
        run: |
          echo "export ANDROID_HOME=$HOME/.buildozer/android/android-sdk" >> $HOME/.bashrc
          echo "export ANDROID_SDK_ROOT=$ANDROID_HOME" >> $HOME/.bashrc
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc
          export ANDROID_HOME=$HOME/.buildozer/android/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3:$PATH
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          sdkmanager --version  # Ellenőrizzük, hogy működik-e

      - name: Android SDK komponensek telepítése
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "cmdline-tools;latest"
          sdkmanager --install "extras;google;m2repository" "extras;android;m2repository"
          sdkmanager --install "platforms;android-33"
          sdkmanager --install "build-tools;33.0.2"
          sdkmanager --install "tools"
          sdkmanager --install "ndk;21.4.7075529"
          sdkmanager --install "cmake;3.18.1"

      - name: Python és Buildozer telepítése
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Buildozer APK készítés
        run: buildozer -v android debug

      - name: APK mentése artifactként
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk

