name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository letöltése
        uses: actions/checkout@v4

      - name: Python telepítése
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Buildozer cache törlése
        run: rm -rf ~/.buildozer

      - name: Buildozer és Android SDK/NDK telepítése
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk
          pip install --upgrade pip setuptools wheel cython virtualenv
          pip install buildozer
          buildozer version

      - name: Kézi python-for-android letöltés és telepítés
        run: |
          mkdir -p ~/.buildozer/android/platform
          git clone --depth 1 https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android
          cd ~/.buildozer/android/platform/python-for-android
          git submodule update --init --recursive
          pip install -e .

      - name: Android SDK és NDK beállítása
        run: |
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk
          export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

      - name: Buildozer inicializálása (ha szükséges)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          cat buildozer.spec
          
      - name: AIDL és egyéb hiányzó SDK komponensek telepítése
        run: |
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "cmdline-tools;latest"
          sdkmanager --install "extras;google;m2repository" "extras;android;m2repository"
          sdkmanager --install "platforms;android-33"
          sdkmanager --install "build-tools;33.0.2"
          sdkmanager --install "tools"
          sdkmanager --install "ndk;21.4.7075529"
          sdkmanager --install "cmake;3.18.1"
          
      - name: APK fordítása
        run: buildozer -v android debug

      - name: APK mentése
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
